### ISSUE TITLE
cp: external/binaryen/lib/libbinaryen.so: No such file or directory

### ISSUE THREAD

**Issue by hama** [wwwg/wasmdec#14]
when i make on Mac, i got this error:
`make installBinaryen
if [ -d "/usr/lib64" ]; then cp external/binaryen/lib/libbinaryen.so /usr/lib64/; else cp external/binaryen/lib/libbinaryen.so /usr/lib/; fi
cp: external/binaryen/lib/libbinaryen.so: No such file or directory
make[1]: *** [installBinaryen] Error 1
make: *** [all] Error 2`

**Comment by wwwg** [comment]
Just added OSX support in the Makefile.
