### ISSUE TITLE
Compile error: src/wasm/WasmUtils.cc:30:8: error: ‘WasmType’ has not been declared

### ISSUE THREAD

**Issue by Lancer233** [wwwg/wasmdec#6]
When I compile this program, I get this error.

src/wasm/WasmUtils.cc:30:8: error: ‘WasmType’ has not been declared
   case WasmType::none:
        ^~~~~~~~
src/wasm/WasmUtils.cc:31:8: error: ‘WasmType’ has not been declared
   case WasmType::unreachable:
        ^~~~~~~~
src/wasm/WasmUtils.cc:34:8: error: ‘WasmType’ has not been declared
   case WasmType::i32:
        ^~~~~~~~
src/wasm/WasmUtils.cc:38:8: error: ‘WasmType’ has not been declared
   case WasmType::i64:
        ^~~~~~~~
src/wasm/WasmUtils.cc:42:8: error: ‘WasmType’ has not been declared
   case WasmType::f32:
        ^~~~~~~~
src/wasm/WasmUtils.cc:46:8: error: ‘WasmType’ has not been declared
   case WasmType::f64:
        ^~~~~~~~

gcc/g++ version 7.2 
DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling

Thank you!

**Comment by wwwg** [comment]
Fixed this specific compilation issue
